### ISSUE TITLE
problem with trezor

### ISSUE THREAD

**Issue by molecular** [markblundeberg/coinsplitter_checkdatasig#3]
First of all: thanks for this awesome work.

Running into an issue (getting the "sorry! something went wrong popup") with following trace:

```
Traceback
Traceback (most recent call last):
  File "/home/nick/bitcoin/coinsplitter_checkdatasig/gui/qt/address_list.py", line 179, in <lambda>
    menu.addAction(_("Split coins (MUL)"), lambda: self.parent.start_coinsplit_mul(address=addr))
  File "/home/nick/bitcoin/coinsplitter_checkdatasig/gui/qt/main_window.py", line 1425, in request_password
    return func(self, *args, **kwargs)
  File "/home/nick/bitcoin/coinsplitter_checkdatasig/gui/qt/main_window.py", line 2193, in start_coinsplit_mul
    coinsplitmul.show_dialog(self, address, password)
  File "/home/nick/bitcoin/coinsplitter_checkdatasig/gui/qt/coinsplitmul.py", line 25, in show_dialog
    d = SplitDialog(*args, **kwargs)
  File "/home/nick/bitcoin/coinsplitter_checkdatasig/gui/qt/coinsplitmul.py", line 55, in __init__
    key = self.wallet.keystore.get_private_key(index, password)
AttributeError: 'TrezorKeyStore' object has no attribute 'get_private_key'
 
Additional information
Electron Cash version: 3.3.1CSplus 
Python version: 3.7.1 (default, Oct 22 2018, 10:41:28) [GCC 8.2.1 20180831] 
Operating system: Linux-4.18.16-arch1-1-ARCH-x86_64-with-arch 
Wallet type: standard 
Locale: en_US 
```

**Comment by markblundeberg** [comment]
Yep, this won't work on hardware wallets. I had to make a choice of either:

1) having the contract keys derived from wallet keys, which means your splitter coins' keys are fully recoverable with your wallet mnemonic.

2) having random contract keys, which means lost funds in case your computer crashes and/or files become corrupted.

I went with the first option, which excludes watching-only and hardware wallets.

**Comment by markblundeberg** [comment]
(That said, I should modify the code a bit so that the menu items don't appear / are disabled, for said wallets.)

**Comment by molecular** [comment]
damn ;-(

thanks for not doing option 2, that would break reasonable assumption hd/hw wallet users make about the recoverability of their keys.

Is there any way to do this with trezor at all?

**Comment by markblundeberg** [comment]
Yes, indirectly:

1. Create a software wallet -- you can save the mnemonic somewhere low-security since you'll only be storing 1000 sats on this wallet.
2. Open coin splitting tool. 
3. Copy the split contract address `bitcoincash:p...` and sent 1000 sats to it, using your hardware wallet software.
4. When it comes time to split, open the software wallet and the splitter tool again -- it should find that utxo that you made.
5. Get a receiving address from your hardware wallet like `bitcoincash:qzzzzzzz`. Enter that into the 'output address' field of the splitter tool.
6. Spend! This sends a single tiny split coin into your hardware wallet.
7. Sweep: Use your hardware wallet software to sweep all coins (including the tiny split coin you just made). The result will be a single large split coin containing your entire wallet balance.

In this way, you never have to move anything but 1000 satoshis out of the hardware wallet.

**Comment by molecular** [comment]
I see! Awesome, thank you so much for this tool and the info!

Maybe you could put that explanation for hw wallet users into your how to use .md?

Regarding removing menu items or greying them out for hw wallets: removing them would be a bad choice, I think, since users would then not know what's going on. Same with greying out: nothing more infuriating than a grayed-out menu item and no explanation. Can there be tooltips on grayed-out menu items? That way you could maybe link an explanation from there?

**Comment by markblundeberg** [comment]
Good point about hiding / disabling. I should just make an error message when they try to open the tool, that explains what is going on. (multisig wallets are also affected)

**Comment by markblundeberg** [comment]
docs updated - 68829025fcfaca3b23d8769740d6bb7fa9493318

**Comment by johneas10** [comment]
Just to confirm, what options should we be selecting from here to spend:

<img width="446" alt="Screenshot 2019-03-25 at 08 57 22" src="https://user-images.githubusercontent.com/18663222/54906853-1d213d00-4edc-11e9-812e-57f84715453b.png">

**Comment by markblundeberg** [comment]
Hey @johneas10, I'd recommend 'combine' and 'redeem with split' for simplicity. Make sure to do this when connected to a BCH server -- if you're connected to BSV server don't worry, it will just reject the transaction and you can try again.

**Comment by johneas10** [comment]
Thanks @markblundeberg 

Think that's me sorted now.
